const String languages = '/languages';
const String translations = '/translations';
const String sendOtp = '/send-otp';
const String verificationOtp = '/verify-account';
const String register = '/certificates/register';
const String login = '/login';
const String pressure = '/pressure';
const String urlHome = '/home-screen';
const String urlChangeNumber = '/plumbers/change-number';
const String form = '/pressure/form';
const String qrCode = '/qrCode/read';
const String assignTo = '/pressure/assigned-to';
const String sendPressure = '/pressure/close';
const String urlMyWallet = '/wallet';
const String urlRanking = '/plumbers/ranks';
const String getRank = '/plumbers/get-rank';
const String updateProfile = '/update-profile';
const String verifyPlumber = '/verify-plumber';
const String addToCartApiRoute = '/cart/add';
const String orders = '/order';
const String orderDetails = '/order/details';
const String addSignature = '/signature';
const String serviceForm = '/form-data/service-form';

const String createCustomer = '/customers/create';
const String createSite = '/create-sites';
const String getCustomers = '/customers/get';
const String getSite = '/sites';

const String keyGetJobCategoriesPat = '/setting/job-category';
const String keyGetTaxPath = '/setting/tax-setting';
const String keyGetServicesPath = '/services';
const String keyGetMaterialsPath = '/materials';
const String keyGetStatusPath = '/status';
const String keyCreateJob = '/job/create';
const String keyCreateServices = '/service/create';
const String keyCrateMaterialsPath = '/materials/create';
const String keyGetJobs = '/job/get';
const String keyCreateClientContact = '/contact/create';
const String keyCreateSiteContact = '/site-contact/create';
const String keyJobUpDateState = '/job/update-status';
const String keyCertUpDateState = '/certificates/update-status';
const String keyGetPaymentTerms = '/payment-terms';

const String keyClosingDates = '/setting/closing-dates';
const String keySchedule = '/schedule';
const String keyOperationHours = '/setting/operation-hours';
const String keyBreakTime = '/break-time';

const String keyForms = '/forms';
const String keyUpdatePassword = '/profile/update-password';
const String keyProfileUpdate = '/profile/update';
const String keyInvoices = '/invoices';
const String keyJobServicesJob = '/job/services-job';
const String keyBusinessType = '/business-type';
const String keyCreateCertificates = '/certificates/create';
const String keyGetCertificates = '/certificates/get';
const String keyGetCertificatesCount = '/certificates/count';
const String keyCreateBreakTime = '/break-time/create';
const String keyDeleteAccount = '/user/delete';
const String keyStoreFormTemplate = '/forms/templates/store';
const String keyGetAllCustomers = '/customers/get';
const String formGetCertificate = '/certificates/customer-certificate?';
//
const String keyProfile = '/profile';
const String keyGetAllFormTemplate = '/forms/templates';
const String keyCreateForm = '/certificates/create';
const String keyGetCountries = '/countries?search=';
// const String keyCompleteProfile = '/complete-register';
//
const String formGetAllCertificates = '/certificates';
const String keyCompletedCert = '/certificates/complete';
const String keyUnCompletedCert = '/certificates/uncompleted';
const String formGetCerCount = '/certificates/count';
