class DomesticEicLists {
  //**-------Lists ------------------ */
  List<String> listDbRef = <String>[
    'DB1',
    'DB2',
    'DB3',
    'DB4',
    'SUB MAIN',
    'Other',
  ];
  List<String> listTypeBSEN = <String>[
    '88 type gG',
    '88 type mG',
    '88 type aM',
    '3036 (S-E)',
    '1361 type 1',
    '1361 type 2',
    '1362',
    '60898 type B',
    '60898 type C',
    '60898 type D',
    '3871 type 1',
    '3871 type 2',
    '3871 type 3',
    '3871 type 4',
    '3871 type B',
    '3871 type C',
    '3871 type D',
    '60947 - 2 MCCB',
    '60947 - 2 ACB',
    '60947 - 2 type D',
    '60947 type B',
    '60947 type C',
    '4293 RCD',
    '61008 RCD',
    '61009 type B',
    '61009 type C',
    '61009 type D',
    '5419 Isolator',
    '60947 - 3 Isolator',
    'N/A',
    'LIMITED',
    'Other',
  ];
  List<String> listRating = <String>[
    '50',
    '60',
    '63',
    '80',
    '100',
    'N/A',
    'Other',
  ];
  List<String> listSupplyConductors = <String>[
    '6',
    '10',
    '16',
    '25',
    '35',
    '50',
    'Other',
  ];
  List<String> listEarth = <String>[
    '4',
    '6',
    '10',
    '16',
    'Other',
  ];
  List<String> listLocations = <String>[
    'Hall',
    'Stairway',
    'Landing',
    'Front Room',
    'Rear Room',
    'Shop Front',
    'Shop Rear',
    'Office',
    'Front Office',
    'Back Office',
    'Other',
  ];
  List<String> listSuppliedFrom = <String>[
    'Main Board',
    'Mains',
    'Sub Mains',
    'DB1',
    'DB2',
    'DB3',
    'DB4',
    'DB5',
    'Other',
  ];
  List<String> listNoOfPhases = <String>[
    'Single',
    'Three',
    'Other',
  ];
  List<String> listBSEN = <String>[
    'Fuse HRC - Type gG',
    'Fuse HRC - Type mG',
    'Fuse HRC - Type aG',
    'Fuse (Semi - enclosed)',
    'Fuse HRC - Type 1',
    'Fuse HRC - Type 2',
    'Fuse HRC Obsolete',
    'MCB Type B',
    'MCB Type C',
    'MCB Type D',
    'MCB - Type 1',
    'MCB - Type 2',
    'MCB - Type 3',
    'MCB - Type 4',
    'MCB - Type B',
    'MCB - Type C',
    'MCB - Type D',
    'MCB Obsolete Type',
    'MCCB',
    'MCCB Obsolete Type',
    'ACB ',
    'ACB Obsolete Type',
    'RCD/RCBO - Type B',
    '61009 RCD/RCBO - Type C',
    'RCD/RCBO - Type D',
    'Isolator',
    'HBC - Type 1',
    'Fuse HBC - Type 1',
    'Fuse HBC',
    'N/A',
    'L/M',
    'Other',
  ];
  List<String> listRatingBSEN = <String>[
    '3',
    '5',
    '6',
    '7.5',
    '10',
    '15',
    '16',
    '20',
    '25',
    '30',
    '32',
    '40',
    '45',
    '50',
    '60',
    '63',
    '80',
    '100',
    '125',
    'N/A',
    'Other',
  ];
  List<String> listCircuitDesignation = <String>[
    'Ring Circuit',
    '1st Floor Lights',
    '2st Floor Lights',
    '3st Floor Lights',
    '4st Floor Lights',
    '5st Floor Lights',
    '1st & Ground Floor Socket',
    'Alarm',
    'Bathroom Shower',
    'Circuit Not Tested',
    'Conveyor Sockets',
    'Cooker',
    'Downstairs Lights',
    'Downstairs Socket',
    'Emergency Lights',
    'En-Suite Shower',
    'Fire Alarm',
    'Flood Lights',
    'Ground Floor Lights',
    'Garage Supply',
    'House Lights',
    'House Ring Main',
    'Hall Lights',
    'Immersion Heater',
    'Kitchen Sockets',
    'Kitchen & Garage Lights',
    'Kitchen & Garage Sockets',
    'Lim',
    'Lights',
    'Lights in Extension',
    'Light Rooms 1,2,3',
    'Lights Garage',
    'Lights Utility Room',
    'Loft',
    'Loft Sockets',
    'Loft Lights',
    'Old Immersion',
    'Old Water Heater',
    'RCD Module',
    'R.C.D',
    'Spare',
    'Sub Main 1',
    'Sub Main 2',
    'Sub Main 3',
    'Sub Main 4',
    'Shower',
    'Shower 1',
    'Shower 2',
    'Shower 3',
    'Shower 4',
    'Shower 5',
    'Upstairs',
    'Shower Bedroom',
    'Shower Near DB',
    'Shower Private Room',
    'Smoke Detectors',
    'Sockets Garage',
    'Sockets',
    'Sockets Outhouse',
    'Sockets Utility Room',
    'Supply to Outbuilding',
    'Tails',
    'Unknown',
    'Upstairs Sockets',
    'Upstairs Lights',
    'Other',
  ];
  List<String> listTypeOfWiring = <String>[
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'Other'
  ];
  List<String> listConductorLive = <String>[
    '1.0',
    '1.5',
    '2.5',
    '4',
    '6',
    '10',
    '16',
    '25',
    '35',
    '50',
    '70',
    '95',
    '120',
    '150',
    '185',
    '240',
    '300',
    '400',
    '500',
    '630',
    'N/A',
    'Other'
  ];
  List<String> listConductorCSA = <String>[
    '1.0',
    '1.5',
    '2.5',
    '4',
    '6',
    '10',
    '16',
    '25',
    '35',
    '50',
    '70',
    '95',
    '120',
    '150',
    '185',
    '240',
    '300',
    '400',
    '500',
    '630',
    'Conduit',
    'Trunking',
    'Armour',
    'MICC',
    'N/A',
    'Other'
  ];
  List<String> listMaxDiscTime = <String>[
    '0.2',
    '0.4',
    '5',
    'Other',
  ];
  List<String> listTypeBSEN2 = <String>[
    '60898',
    '3036',
    '1261',
    '1262',
    '88',
    '3871',
    '60947',
    '4293',
    '61008',
    '61009',
    '5419',
    '60947',
    'N/A',
    'LIMITED',
    'Other',
  ];
  List<String> listTypeCurrentDevice = <String>[
    'A',
    'B',
    'C',
    'D',
    'gG',
    'P',
    'K',
    'Z',
    'ACB',
    'aM',
    'mG',
    '(S-E)',
    '1',
    '2',
    '3',
    '4',
    'Other'
  ];
  List<String> listShortCircuitCapacity = <String>[
    '1',
    '1.5',
    '2',
    '3',
    '4',
    '4.5',
    '5',
    '6',
    '7.5',
    '9',
    '10',
    '12.5',
    '15',
    '16',
    '16.5',
    '18',
    '20',
    '22',
    '25',
    '32',
    '33',
    '35',
    '40',
    '45',
    '50',
    '80',
    'N/A',
    'Other',
  ];
  List<String> listTypeRCD = <String>[
    'AC',
    'A',
    'B',
    'F',
    'Type 1',
    'Type 2',
    'N/A',
    'Other',
  ];
  List<String> listRCDAtDelta = <String>[
    '30',
    '100',
    'N/A',
    'Other',
  ];
}
