class ApplianceListValues {
  List<String> listApplianceDescription = <String>[
    'Adapter',
    'Air Freshener',
    'Answerphone',
    'Blender',
    'Blu-Ray Player',
    'Battery Charger',
    'Computer',
    'Coffee Maker',
    'Cash Register',
    'Cooker',
    'CD Player',
    'Coffee Machine',
    'Convector Heater',
    'Cooker',
    'Clock Radio',
    'Charger',
    'Dishwasher',
    'Dryer',
    'Drinks Machine',
    'Drill',
    'DVD Player',
    'Electric Blanket',
    'Extension Lead',
    'Fan',
    'Fax Machine',
    'Floor Polisher',
    'Freezer',
    'Fridge',
    'Fridge Freezer',
    'Fryer',
    'Fan Heater',
    'Games Console',
    'Hair Dryer',
    'Hot',
    'IEC Lead',
    'Iron',
    'IT Equipment',
    'Kettle',
    'Laptop',
    'Lamp',
    'Luminaire',
    'Microwave',
    'Monitor',
    'Oven',
    'Overhead Projector',
    'Photocopier',
    'Printer',
    'Projector',
    'Radio',
    'Scanner',
    'Transformer',
    'Tumble Dryer',
    'Toaster',
    'Telephone',
    'Trouser Press',
    'Vacuum Cleaner',
    'Water Cooler',
    'Washing Machine',
    'Other',
  ];
  List<String> listApplianceLocation = <String>[
    'Hall',
    'Stairway',
    'Landing',
    'Front Room',
    'Rear Room',
    'Shop Front',
    'Shop Rear',
    'Office',
    'Front Office',
    'Back Office',
    'Other',
  ];
  List<String> listApplianceClass = <String>[
    '2',
    'IEC',
    '1',
    '2a',
    '2b',
    '3',
    'Other',
  ];
  List<String> listApplianceInspection = <String>[
    'N/A',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '18',
    '24',
    '36',
    'Other'
  ];
  List<String> listTestRepairCode = <String>[
    'N/A',
    'A - Replace plug',
    'B - Rewire plug',
    'C - Fit BS1363 sleeved plug',
    'D - Fit Rubber Plug',
    'E- Fit inline switch',
    'F - Replace IEC lead',
    'G - Replace lead',
    'H - Other',
  ];
  List<String> listTestVisualCheck = <String>[
    'True',
    'False',
    'Other',
  ];
}
