class ListGasTestPurge {
  List<String> listBoilerMake = <String>[
    'Alpha',
    'Ariston',
    'Baxi',
    'Biasi',
    'Bosch',
    'Chaffoteaux',
    'Cannon',
    'Ferroli',
    'Electrolux',
    'Glow Worm',
    'Halstead',
    'Ideal',
    'Johnson',
    'KESTON',
    'Main',
    'Myson',
    'Nu-Way',
    'Ocean',
    'Potterton',
    'Ravenheat',
    'Riello',
    'Saunier',
    'Sime',
    'Thorn',
    'Valiant',
    'Valour',
    'Vokera',
    'Worcester',
    'Other',
  ];

  List<String> listApplianceMake = <String>[
    'Alpha',
    'Ariston',
    'Baxi',
    'Biasi',
    'Bosch',
    'Chaffoteaux',
    'Cannon',
    'Ferroli',
    'Electrolux',
    'Glow Worm',
    'Halstead',
    'Ideal',
    'Johnson',
    'KESTON',
    'Main',
    'Myson',
    'Nu-Way',
    'Ocean',
    'Potterton',
    'Ravenheat',
    'Riello',
    'Saunier',
    'Sime',
    'Thorn',
    'Valiant',
    'Valour',
    'Vokera',
    'Worcester',
    'Other',
  ];
}
