class LandLordListsForm {
  List<String> listApplianceDesignation = <String>[
    '1st Floor',
    '2st Floor',
    '3st Floor',
    'Admin Office',
    'Bed Room',
    'Board Room',
    'Canteen',
    'Cloak Room',
    'Cupboard',
    'Conservatoire',
    'Corridor',
    'Dining Room',
    'Garage',
    'Ground Floor',
    'Kitchen',
    'Landing',
    'Living Room',
    'Meeting Room',
    'Office',
    'Outbuilding',
    'Reception',
    'Study',
    'Training Room',
    'Utility',
    'Warehouse',
    'Other',
  ];

  List<String> listType = <String>[
    'Air Conditioning',
    'Boiler',
    'Central Heating',
    'Cooker',
    'Hob',
    'Heater',
    'Other',
  ];

  List<String> listMake = <String>[
    'Alpha',
    'Ariston',
    'Baxi',
    'Biasi',
    'Bosch',
    'Chaffoteaux',
    'Cannon',
    'Ferroli',
    'Electrolux',
    'Gledhill',
    'Glow Worm',
    'Halstead',
    'Heatrae',
    'Ideal',
    'Johnson',
    'Keston',
    'Main',
    'Myson',
    'Nu-Way',
    'Ocean',
    'Potterton',
    'Radient',
    'Remeha',
    'Ravenheat',
    'Riello',
    'Saunier',
    'Sime',
    'Thorn',
    'Vailant',
    'Viessmann',
    'Valour',
    'Vokera',
    'Worcester',
    'Other',
  ];

  List<String> listYesNo = <String>[
    'Yes',
    'No',
    'N/A',
    'Other',
  ];
  List<String> listPassFail = <String>[
    'Pass',
    'Fail',
    'N/A',
    'Other',
  ];

  List<String> listFlueType = <String>[
    'OF',
    'RS',
    'FL',
    'N/A',
    'Other',
  ];

  List<String> listNumbers = <String>[
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
  ];
}
